### ISSUE TITLE
build-godot hangs forever

### ISSUE THREAD

**Issue by jdbecker** [CapsCollective/godot-actions#1]
I'd love to know if I'm the only one having this issue: when I try to use the `build-godot` action via the step:
```
- name: Build and upload artifacts for all platforms
  uses: CapsCollective/godot-actions/build-godot@v1.0
  with:
    godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
```

I am finding that it hangs indefinitely. I've tried checking out some of your other projects to see if you are getting this to work and maybe I'm just doing something wrong. The newest Godot project at CapsCollective's public repos seems to be `sunflower` so I tried copying this workflow almost exactly and found my workflow would hang when I ran it at this point: https://github.com/CapsCollective/sunflower/blob/develop/.github/workflows/verify-develop.yml#L58

I'm not really sure how to debug this because I'm not getting hardly any output, and when I try to reproduce locally, it finishes successfully.

Any help appreciated!
